//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppointmentID { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public int PersonID { get; set; }
        public int DoctorID { get; set; }
        public string Prescription { get; set; }
        public string AppointmentState { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
