//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int PersonID { get; set; }
        public int EmployeeID { get; set; }
        public int DepartmentID { get; set; }
        public decimal Salary { get; set; }
        public decimal WorkHours { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
